# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/neural/neural.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural || ORIG_REF_NAME==neural}]

# IP: bd/neural/ip/neural_processing_system7_0_0_1/neural_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_processing_system7_0_0 || ORIG_REF_NAME==neural_processing_system7_0_0}]

# IP: bd/neural/ip/neural_axi_gpio_0_0/neural_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_axi_gpio_0_0 || ORIG_REF_NAME==neural_axi_gpio_0_0}]

# IP: bd/neural/ip/neural_processing_system7_0_axi_periph_0/neural_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==neural_processing_system7_0_axi_periph_0}]

# IP: bd/neural/ip/neural_rst_processing_system7_0_100M_0/neural_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==neural_rst_processing_system7_0_100M_0}]

# IP: bd/neural/ip/neural_auto_pc_0/neural_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_auto_pc_0 || ORIG_REF_NAME==neural_auto_pc_0}]

# XDC: bd/neural/ip/neural_processing_system7_0_0_1/neural_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==neural_processing_system7_0_0 || ORIG_REF_NAME==neural_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/neural/ip/neural_axi_gpio_0_0/neural_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==neural_axi_gpio_0_0 || ORIG_REF_NAME==neural_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/neural/ip/neural_axi_gpio_0_0/neural_axi_gpio_0_0_ooc.xdc

# XDC: bd/neural/ip/neural_axi_gpio_0_0/neural_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==neural_axi_gpio_0_0 || ORIG_REF_NAME==neural_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/neural/ip/neural_rst_processing_system7_0_100M_0/neural_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==neural_rst_processing_system7_0_100M_0}]

# XDC: bd/neural/ip/neural_rst_processing_system7_0_100M_0/neural_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==neural_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==neural_rst_processing_system7_0_100M_0}]

# XDC: bd/neural/ip/neural_rst_processing_system7_0_100M_0/neural_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/neural/ip/neural_auto_pc_0/neural_auto_pc_0_ooc.xdc

# XDC: bd/neural/neural_ooc.xdc
