webtalk_init -webtalk_dir /nfs/home/sasl/eleves/ei-se/3701019/Bureau/TP_CODESIGN/Neuron/neural/neural.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "ven. mars 15 17:58:34 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2gvu97p3j95rl40dbatffvoueu" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1552667150000" -context "sdk\\\\bsp/1552667150000"
webtalk_add_data -client sdk -key hwid -value "1552662291000" -context "sdk\\\\bsp/1552667150000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1552667150000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1552667150000"
webtalk_add_data -client sdk -key uid -value "1552667218000" -context "sdk\\\\application/1552667218000"
webtalk_add_data -client sdk -key hwid -value "1552662291000" -context "sdk\\\\application/1552667218000"
webtalk_add_data -client sdk -key bspid -value "1552667150000" -context "sdk\\\\application/1552667218000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1552667218000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1552667218000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1552667218000"
webtalk_transmit -clientid 3819073795 -regid "" -xml /nfs/home/sasl/eleves/ei-se/3701019/Bureau/TP_CODESIGN/Neuron/neural/neural.sdk/webtalk/usage_statistics_ext_sdk.xml -html /nfs/home/sasl/eleves/ei-se/3701019/Bureau/TP_CODESIGN/Neuron/neural/neural.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /nfs/home/sasl/eleves/ei-se/3701019/Bureau/TP_CODESIGN/Neuron/neural/neural.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
